import { CopyChip, DefinitionList } from "@/components/ui/primitives";
import { formatUtc } from "@/lib/format";
import type { Provenance } from "@/lib/api/types";

/**
 * Everything needed to reproduce this number.
 *
 * All of it is copyable, because provenance that has to be retyped is
 * provenance that gets retyped wrong. Between the snapshot hash, the run id,
 * the code version and the config hash, `pramaanx backtest` can be pointed at
 * the exact state that produced the figure above.
 */
export function ProvenancePanel({ provenance }: { provenance: Provenance }) {
  return (
    <div className="space-y-3">
      <div className="flex flex-wrap gap-1.5">
        <CopyChip label="snapshot" value={provenance.snapshot_hash} />
        <CopyChip label="run" value={provenance.run_id} />
        <CopyChip label="code" value={provenance.code_version} />
        <CopyChip label="config" value={provenance.config_hash} />
      </div>

      <DefinitionList
        items={[
          { label: "Snapshot built", value: formatUtc(provenance.snapshot_built_at) },
          { label: "Calibration", value: <code className="text-2xs">{provenance.calibration}</code> },
          { label: "Alert policy", value: <code className="text-2xs">{provenance.alert_policy}</code> },
          { label: "Generated by", value: provenance.generated_by.join(", ") || "—" },
        ]}
      />

      <div>
        <p className="label">Model versions</p>
        <ul className="mt-1 space-y-0.5">
          {Object.entries(provenance.model_versions).map(([component, version]) => (
            <li key={component} className="flex justify-between gap-3 text-2xs">
              <span className="muted">{component}</span>
              <code>{version}</code>
            </li>
          ))}
        </ul>
      </div>

      <p className="text-2xs muted">
        A forecast without a snapshot hash cannot be audited for leakage, and an unauditable
        forecast is not a forecast. That rule is enforced by the schema, not by this panel.
      </p>
    </div>
  );
}
